version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./laravel-app:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./laravel-app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db-data:
